---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-env
data:
  dbhost: "postgresql"
  DEBAG: "false"
  #создастся файл с именем default.conf и заполнит его этим текстом снизу
  default.conf: |
    server {
      listen 80 default_server;
      server_name _;
      default_type text/plane;
      location / {
        return 200 'Nihao!!\n$hostname\n';
        #return 200 '$hostname\n';
      }
      location /files {
        alias /data;
        autoindex on;
        client_body_temp_path /tmp;
        dav_methods PUT DELETE MKCOL COPY MOVE;
        create_full_put_path on;
        dav_access user:rw group:rw all:r;
      }
    }
...