apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  #если если один джоб еще не закончил работу а время уже начинать второму, то конкретно эта настройка позволяет одновременный запуск нескольких джобов,
  #это опасно, можно наплодить джобов и завалить кластер.
  #Второе знач "Forbid" - бэст практика, так же есть "Replace" - заменит старый джоб на новый
  concurrencyPolicy: Allow
  #допуск времени запоздания запуска в секундах
  #указывается меньше чем время до запуска следующего джоба,
  #но не меньше прим.10сек, чтобы шедулер успел поставить задачу
  startingDeadlineSeconds: 20
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
            - name: hello
              image: quay.io/prometheus/busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster;
          restartPolicy: Never

