---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  #способ обновления реплик
  strategy:
#    type: Recreate
    rollingUpdate:
      #кол. реплик которые сразу можно поднять
      maxSurge: 25%
      #кол. реплик которые сразу можно гасить
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: nginx:1.20-alpine
          name: nginx
          env:
            - name: TEST
              value: foo
            - name: TEST_1
              valueFrom:
                secretKeyRef:
                  name: test
                  key: test1
            #здесь приведены несколько частоупотребимых Donward API
            - name: __NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: __POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: __POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: __POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: __NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: __POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          #переменные взятые из configmap
          envFrom:
            - configMapRef:
                name: my-configmap-env
          ports:
            - containerPort: 80
          resources:
            requests:
              #милиц-cpu 1000мили-cpu = 1ядро
              cpu: 10m
              #мегабайты
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d/
            - name: podinfo
              mountPath: /etc/podinfo
              #пример использования HostPath
#            - name: data
#              mountPath: /files
              #пример использования EmptyDir
            - name: data
              mountPath: /files
      volumes:
        - name: config
          configMap:
            name: my-configmap-env
        #это тоже Donward API некоторые данные о...
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        #пример использования HostPath
#        - name: data
#          hostPath:
#            path: /etc/kubernetes
        #пример использования EmptyDir
        - name: data
          emptyDir: {}
...