---
apiVersion: v1
#тип описываемого обьекта
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - image: nginx:1.20-alpine
      name: nginx
      ports:
        #     не несет физического смысла для подов
      - containerPort: 80
#        второй контейнер в поде
    - image: nginx:1.20-alpine
      name: nginx-2
      ports:
        #     не несет физического смысла для подов
        - containerPort: 80
...