#отлаживает внутрикластерное взаимодействие
apiVersion: v1
kind: Service
metadata:
  #имя сервиса будет ip адресом сервиса
  name: my-service
  namespace: default
spec:
  ports:
    - port: 80 #сюда будет приходить трафик
      targetPort: 80 #туда будет отправляться трафик
  selector:
    app: my-app #очень важно, он отправит трафик на приложения только с этим лэйблом
  type: ClusterIP #этот тип проставляется по умолчанию если его не указать