replicas: 3

image:
  repository: nginx
  tag: 1.12

port: 80

resources:
  requests:
    cpu: 80m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

annotations:
  test: ok

env:
  MYSQL_PORT: 3306
  MYSQL_USER: root